 <?php

/* 
 * This class is responcible for the reports of KOT
 * Author: Abhishek Kumar Mishra
 * Created Date: 18/10/2014
 */

class HotelReportsKOT
{
	
	function __construct()  
	{	
					$this->db = new database(DATABASE_HOST,DATABASE_PORT,DATABASE_USER,DATABASE_PASSWORD,DATABASE_NAME);
					$this->validity = new ClsJSFormValidation();
					$this->Form = new ValidateForm();
					$this->auth=new Authentication();
					$this->noti=new Notification();
					$this->Helper=new HotelReportHelper();
					
	}
	
	
	function KOTReportFilter($kot_for,$room_no_id,$report_date,$kot_type){
		?>
        <div class="col-lg-12">
					<div class="block-flat" style="min-height:225px !important;">
                      <div class="header">							
							<h4>KOT REPORTING </h4>
						</div>
						<div class="content">
<form method="get" action="kt_reporting.php" enctype="multipart/form-data" id="" name="searchUser" >

    <div class="col-lg-3">
    <div class="form-group"> 
    <select  class="form-control" name="kot_for">
                <option value="">-- Select Kot Report For --</option>
                <option value="guest" <?php if($_REQUEST['kot_for']=='guest') { echo 'selected="selected"';}?> >Guest</option>
                <option value="staff" <?php if($_REQUEST['kot_for']=='staff') { echo 'selected="selected"';}?>>Staff</option>
                <option value="visitors" <?php if($_REQUEST['kot_for']=='visitors') { echo 'selected="selected"';}?>>Visitors</option>
    </select>
    </div>
    </div>  
    
    <div class="col-lg-3">
    <div class="form-group" id="refroomlisting"> 
    <select name="room_no_id" class="form-control">
    <option value="">-- Room No.--</option>
		<?php
		$sql="select id,room_no,assigned,deleted from ".HMS_ROOM." where deleted='0'";
		$result = $this->db->query($sql,__FILE__,__LINE__);
		while($row = $this->db->fetch_array($result))
				{
					?>
                    <option value="<?php echo $row['id'];?>" <?php if($_REQUEST['room_no_id']==$row['id']) { echo 'selected="selected"';}?>><?php echo 'Room'.$row['room_no'];?></option>
                    <?php
				}
				?>
	</select>
     </div>
    </div>
    
    <div class="col-lg-3">
    <div class="form-group">
             <div class="input-group date datetime" data-min-view="2" data-date-format="yyyy-mm-dd">
            <input class="form-control"  name="report_date" size="16" type="text" value="<?php echo $_REQUEST['report_date'];?>"  >
            <span class="input-group-addon btn btn-primary"><span class="glyphicon glyphicon-th"></span></span>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
    <div class="form-group" id="refroomlisting"> 
    <select name="kot_type" class="form-control">
    <option value="">-- KOT Type--</option>
    <option value="non_cmtry" <?php if($_REQUEST['kot_type']=='non_cmtry') { echo 'selected="selected"';}?>>Non-Complementary</option>
    <option value="cmtry" <?php if($_REQUEST['kot_type']=='cmtry') { echo 'selected="selected"';}?>>Complementary</option>
	</select>
     </div>
    </div>
    
     <div class="col-lg-4">
         <div class="form-group"> 
        <button class="btn btn-primary" type="submit" value="View Report" name="submit">View Report</button>
        </div>
        </div>              
            </form>
						</div>
					</div>				
				</div>
        <?php 
	}
	
	
	
	function SalesKOTReport($kot_for,$room_no_id,$report_date,$kot_type)
	{
		$sql="select * from ".HMS_KOT." where 1";
		if($kot_for)
		  {
			  $sql .= " and kot_for ='".$kot_for."'";
		  }
		  if($room_no_id)
		  {
			  $sql .= " and room_id  ='".$room_no_id."'";
		  }
		  if($report_date)
		  {
			  $sql .= " and Date(order_datetime)  ='".$report_date."'";
		  }
		  if($kot_type)
		  {
			  $sql .= " and kot_type  ='".$kot_type."'";
		  }
		  $sql .= " order by created desc";
		  $result = $this->db->query($sql,__FILE__,__LINE__);
		  $cnt =$this->db->num_rows($result);
		?>
        <div class="col-md-12">
					<div class="block-flat">
                    
						<div class="header">
                        <h4>Report List</h4>
                      </div>
						<div class="content">
                        
                        <table id="example" class="display" cellspacing="0" width="100%">
				<thead>
					<tr>
			<th>S.No.</th>
            <th>KOT FOR</th>
            <th>KOT TYPE</th>
            <th>KOT AMOUNT</th>
            <th>STATUS</th>
            <th>ORDER AT</th>
            <th>GENERATED BY</th> 
            <th>ACTION</th>
           </tr>
				</thead>
             <tbody>
              <?php
		if($cnt>0)
		{
				$i=1;
				while($row = mysql_fetch_assoc($result))
				{
					?>
                    <tr style="color:#000 !important;">
					<td><?php echo $i;?></td>
					<td><?php echo ucwords($row['kot_for']);?></td>
					<td><?php  if($row['kot_type']=='cmtry'){ echo 'Complementary';} else { echo 'Non-Complementary';}?></td>
					<td><?php echo number_format($row['kot_total'],2);?></td>
					<td><?php echo $row['paid_status'];?></td>
					<td><?php echo $row['order_datetime'];?></td>
					<td><?php echo $this->GetUSERNAMEbyUSerID($row['user_id']);?></td>
					<td><a href="printkot.php?kt_id=<?php echo $row['id'];?>" class="fancybox fancybox.iframe"><i class="fa fa-arrow-up"></i> View</a></td>
					</tr>
                 <?php
				 $i++;
				}
		}
		?>		
	</tbody>
			</table>
          </div>
					</div>				
				</div>
        <?php 
	}
	
	
	function GetUSERNAMEbyUSerID($userId){ 
		$sql="select * from ".HMS_USER." where id='".$userId."'";
		$result = $this->db->query($sql,__FILE__,__LINE__);
		$row = $this->db->fetch_array($result);
		return $row['username'];
	}
	
	
	
	
	
	
	
	
	

}