<?php 

$record = $this->paginator; 
$totalrec = $this->totalrec;
$params = $this->params;
//$CountPM = $this->TotalPmGroupCount;
//echo "<pre>"; print_r($this->pmdescbypmgroupID);





$auth = Zend_Auth::getInstance();
$authStorage = $auth->getStorage();
//echo "<pre>"; print_r($authStorage->read()); die;
$role = $authStorage->read()->role;

////



?>



<!--    <script src="http://code.jquery.com/jquery-1.11.1.js"></script>-->
    <script src="/js/jquery-1.8.3.js"></script>
    <link href="/css/uibasetheme/jquery-ui.css" rel="Stylesheet" type="text/css" />
    <link href="/css/jquery-ui.css" rel="stylesheet" type="text/css" />
    
   <!-- <script src="js/jquery-1.6.4.min.js" type="text/javascript"></script>-->
    <script src="/js/jquery.ui.core.js" type="text/javascript"></script>
    <script src="/js/jquery.ui.widget.js" type="text/javascript"></script>
    <script language="javascript" type="text/javascript" src="showhide.js"></script>
    <script src="/js/jquery-ui.js"></script>
   
    
    
    <script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript">
		$(document).ready(function() {	
					$("a#open_issue_count").fancybox({
					'width' : "80%",
					'height' : "80%",
					'speedIn'		:	600, 
					'speedOut'		:	200, 
					'overlayShow'	:	true
					});	
				});	
</script>
    
    
    

<script type="text/javascript">
$(function() {
		$( "#distance_from" ).datepicker({
			showOn: "button",
			buttonImage: "<?php echo $this->siteurl; ?>calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
			buttonText:'From date'
		});
		$( "#distance_to" ).datepicker({
			showOn: "button",
			buttonImage: "<?php echo $this->siteurl; ?>calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
			buttonText:'To date'
		});
                $( "#date_raised" ).datepicker({
			showOn: "button",
			buttonImage: "<?php echo $this->siteurl; ?>calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
                        constrainInput: false,
			buttonText:'To date'
		});
                 $( "#date_due" ).datepicker({
			showOn: "button",
			buttonImage: "<?php echo $this->siteurl; ?>calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
                        constrainInput: false,
			buttonText:'To date'
		});
                $( "#date_close" ).datepicker({
			showOn: "button",
			buttonImage: "<?php echo $this->siteurl; ?>calendar.gif",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true,
                        constrainInput: false,
			buttonText:'To date'
		});
		
		
		
	});
</script>
 <script>
          $(function () {
              $('.tabs').tabs(
                  { heightStyle: 'auto'});
          });
     </script>
      <script>
        $(function () {
            $('.accordion').accordion({
                collapsible: true,
                heightStyle: 'content',
                autoHeight: false,
                active:'none'
            });
        });
    </script>
     <script>
$(function() {
var availableTags = [
"Emp 1",
"Emp 2",
"Emp 3",
"Emp 4",
"Emp 5",
"Emp 6",
"Emp 7",
"Emp 8",
"Emp 9",
"Emp 10"
];
$( "#tags" ).autocomplete({
source: availableTags
});
});
</script>
<script type="text/javascript">
function call_log_Validate()
{  
         var date_time_rgx = /(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})/;
	 if(document.getElementById("issue_source").value=="")
	{
	 alert("Please select issue source.");
	 document.getElementById("issue_source").focus();
	 return false;
	}
        if(document.getElementById("issue_status").value=="")
	{
	 alert("Please select issue status.");
	 document.getElementById("issue_status").focus();
	 return false;
	}
        
        if(document.getElementById("impact").value=="")
	{
	 alert("Please select impact.");
	 document.getElementById("impact").focus();
	 return false;
	}
        if(document.getElementById("date_raised").value=="")
	{
	 alert("Please select date raised.");
	 document.getElementById("date_raised").focus();
	 return false;
	}
        if(document.getElementById("tenant_affected").value=="")
	{
	 alert("Please select tenant affected.");

	 document.getElementById("tenant_affected").focus();
	 return false;
	}
        if(document.getElementById("item_description").value=="")
	{
	 alert("Please select item description.");
	 document.getElementById("item_description").focus();
	 return false;
	}
        
  return true;
}
</script>
<script>
    function getVatueForpmform()
{  
    var PmID = document.getElementById("pm_group").value;
   
    location.href='/data/index/pmid/'+PmID;
}


</script>
<script>
$(function () {
$( "#access_code" ).change(function(e) {

$.getJSON("/data/ajax-getplandate/site_id/"+$( "#access_code" ).val()+"/plan_id/"+$( "#plan_id" ).val(), function(data){
var k = $( "#access_code" ).val();
$('#site_name').val(k);
$('#plan_date').val(data.planned_maintenance_date);
$('#actual_date').val(data.actual_maintenance_date);
});

$.getJSON("/issuetracker/ajax-getissuecount/site_id/"+$( "#access_code" ).val(), function(data){
//alert(data.TotalIssue);
var url;
if(data.TotalIssue>0){
url = "/issuetracker/open-issue/siteId/"+$( "#access_code" ).val();
}else{
url = "#";    
}
$('#open_issue_count').text(data.TotalIssue);
$('#open_issue_count').attr("href", url);
//$('#actual_date').val(data.actual_maintenance_date);

});
    


});
});



     </script>

<div class="content">

    <ul class="breadcrumb" style="top: 53px;">

            <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>

            <li class="active">Data</li>

        </ul>



<div class="container-fluid">

		

 

    <style>
        .formseparetor{
            
  padding: 1px;
        }
        .labeladd{
             width: 138px; float: left;
             
        }
        .selectadd {
                    width: 55%;
                    height: 24px;
                   
        }
        
        .frmset {
                
                float: left;
                width: 460px;
        }
        .frmset1 {
                
                float: left;
                margin-left: 117px;
        }
        .selectadd1 {
                    width: 100%;
                    height: 29px;
        }
        
    </style>
    
        
       
            <div>
                <form method="POST" action="" onsubmit="" >
                    <fieldset>
                     <div class="frmset">
                       <div class="formseparetor">
                           <label class="labeladd">PM Type :</label>
                           <select class="selectadd" name="pm_type" id="pm_type">
                               <option value="">---Select---</option>
                               <option value="">SITE PM</option>
                           </select>
                       </div>
                         <div class="formseparetor">
                           <label class="labeladd">PM Name :</label>
                           <select class="selectadd" name="plan_id" id="plan_id">
                           <option value="">---Select---</option>
                                <?php
				  foreach($this->PmPlan as $pp)
				  {
				  ?>
                               <option value="<?php echo $pp['plan_id']?>"><?php echo $pp['plan_name']?></option>
                               <?php
                                  }
                                  ?>               
                           </select>
                       </div>
                         <div class="formseparetor">
                           <label class="labeladd">Access Code :</label>
                           <select class="selectadd" name="access_code" id="access_code">
                           <option value="">---Select---</option>
                            <?php
				  foreach($this->AccessCode as $ac)
				  {
				  ?>
                                <option value="<?php echo $ac['site_id']?>"><?php echo $ac['login_id']?> | <?php echo $ac['site_id']?> | <?php echo $ac['site_name']?> | <?php echo $ac['tech_name']?></option>
                                <?php
                                  }
                                  ?>
                           </select>
                       </div>
                         <div class="formseparetor">
                           <label class="labeladd">Site Name :</label>
                           <select class="selectadd" name="site_name" id="site_name">
                               <option value="">---Select---</option>
                               <?php
				  foreach($this->SiteList as $sl)
				  {
				  ?>
                               <option value="<?php echo $sl['consolidate_id']?>"><?php echo $sl['name']?></option>
                               <?php
                                  }
                                  ?>
                            </select>
                       </div>
                         
                         <div class="formseparetor">
                           <label class="labeladd">Plan Date :</label>
                           <input class="inputadd" type="text" name="plan_date" value="" id="plan_date" readonly=""/>
                       </div>
                         
                       <div class="formseparetor">
                           <label class="labeladd">Actual Date :</label>
                           <input class="inputadd" type="text" name="actual_date" id="actual_date" readonly=""/>
                       </div>
                         <div class="formseparetor">
                           <label class="labeladd">PM Status :</label>
                           <select class="selectadd" name="pm_status" id="pm_status">
                               <option value="">---Select---</option>
                               <option value="">1</option>
                               <option value="">2</option>
                            
                           </select>
                       </div>
                       <div class="formseparetor">
                           <label class="labeladd">PM Group :</label>
                           <select class="selectadd" name="pm_group" id="pm_group" onchange="getVatueForpmform()">
                                <option value="">---Select---</option>
                                <?php
				  foreach($this->PmGroup as $pm)
				  {
				  ?>
                                <option value="<?php echo $pm['id']?>" <?php if($params['pmid']== $pm['id']){ ?> selected="selected" <?php } ?>><?php echo $pm['pm_group']?></option>
                            
                               <?php
                                  }
                                  ?>                
                            </select>
                       </div>
                         
                         <div class="formseparetor">
                           <label class="labeladd">Remarks :</label>
                           <input class="inputadd" type="text" name="remarks"/>
                               
                       </div>
                         
                  </div>
                    <div class="frmset1">
                        <div class="formseparetor">
                           <label class="labeladd">Percentage Done :</label>
                           <a>----</a> 
                       </div>
                        <br>
                        <br>
                        <div class="formseparetor" id="issue_cont">
                            <label class="labeladd">Open Issues :  <a href="#" class="iframe" id="open_issue_count" >0</a> </label>
                           
                       </div>
                       <br>
                       <br>
                       <div class="formseparetor">
                           <label class="labeladd">Audit Access Code :</label>
                           <input class="inputadd" type="text" name="audit_access_code" list="AuditAccessCode"/>
                            <datalist id="AuditAccessCode" class="selectadd">
                                <option id="" value="1"></option>
                                <option id="" value="2"></option>
                                <option id="" value="3"></option>                
                            </datalist>
                       </div>
                        <div class="formseparetor">
                            <br>
                            <label class="labeladd"></label>
                            <button style="line-height: 13px!important; width: 253px!important;" value="Close" name="submit" class="btn btn-primary" type="submit">Generate Audit List</button>
                        </div>
                     </div>
                     <div class="frmset1">
                           <button style="line-height: 13px!important; width: 127px!important;" value="Save" name="submit" class="btn btn-primary" type="submit">Submit PM</button>
                           <br>
                           <br>
                           <button style="line-height: 13px!important; width: 127px!important;" value="Close" name="submit" class="btn btn-primary" type="submit">Audit PM</button>
                           <br>
                           <br>
                           <button style="line-height: 13px!important; width: 127px!important;" value="Close" name="submit" class="btn btn-primary" type="submit">Sign PM</button>
                           <br>
                           <br>
                           <button style="line-height: 13px!important; width: 127px!important;" value="Close" name="submit" class="btn btn-primary" type="submit">Decline PMD</button>
                           <br>
                           <br>
                           <button style="line-height: 13px!important; width: 127px!important;" value="Close" name="submit" class="btn btn-primary" type="submit">Log Site Issue</button>
                             </div>
                   </fieldset>
                    <hr>
                    
                </form>  
            </div>
<!--********************************************************************************-->
<!--<div class="tabs" id="table">
</div>-->
<style>
    .inputpm
        {
              display: inline-block;
  height: 19px!important;
  padding: 1px 4px!important;
  margin-bottom: 3px!important;
  font-size: 14px!important;
  line-height: 20px!important;
  color: #555555!important;
        }
       
        .selectpm 
        {
                    width: 100%!important;
                    height: 24px!important;
        }
    </style>
<div>
    <form method="POST" action="" onsubmit="" >
                    
                
                    <?php
                    $pmdescbypmgroupID = $this->pmdescbypmgroupID;
                    if(count($pmdescbypmgroupID)>0)
                    {
                        ?>
        <table border="1">
                    <tr>
                            <th>SELECT</th>
                            <th>ITEM VALUE</th>
                            <th>ITEM REMARKS</th>
                            <th>DESCRIPTION</th>          
                    </tr>
                        <?php
                    
				  foreach($this->pmdescbypmgroupID as $pd)
				  {
                                      $data = new Application_Model_Data();
                                      $itemValues = $data->GetItemValueByDescID($pd['desc_id']);
                                      
				  ?>
                    
                            <tr>
                            <td>
                                <input type="checkbox" name="checkbox"  style="width: 54px!important;"/>
                            </td>
                            <td>
                                
                                <select class="selectpm" name="item_value" id="item_value">
                                    <option value="">---Select---</option>
                                    <?php
                                    foreach($itemValues as $k){
                                        ?>
                                    <option value="<?php echo $k['itemvalue_id'];?>"><?php echo $k['item_value'];?></option>
                                    <?php
                                    }
                                    ?>
                                 </select>
                                
                            </td>
                            <td>
                                <input class="inputpm" type="text" name="desc"/>
                            </td>
                            <td>
                                <?php echo $pd['description']?>
                            </td>
                            </tr>
                            
                            <?php
                                  }
                                  
                                  ?>
                            </table>
                    <button style="line-height: 13px!important; width: 127px!important; float:right!important;   margin-right: 48px!important; margin-top: 20px!important;" value="Save" name="submit" class="btn btn-primary" type="submit">Save</button>
                            <?php
                    }
                                  ?>
                    
                    
                
      
            </form>
        </div>

<!--****************************************************************************-->
</div>
   

</div>


    

   

